[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "AWS IoT TwinMaker Extension"
description = "The simplest python extension example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Path (relative to the root) of changelog
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = "https://github.com/hwandersman/kit-extension-template"

# One of categories for UI.
category = "IoT"

# Keywords for the extension
keywords = ["kit", "IoT", "Digital Twin"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.asset_converter" = {}
"omni.services.core" = {}
"omni.services.transport.server.http" = {}

# Main python module this extension provides, it will be publicly available as "import omni.iot.twinmaker".
[[python.module]]
name = "omni.iot.twinmaker"

[python.pipapi]
requirements = ['scipy']
use_online_index = true

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
